name: build-and-release

on:
  push:
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/"
      - "README.md"
    branches:
      - main
jobs:
  constants:
    runs-on: ubuntu-latest
    outputs:
      JAVA-VERSION: "11"
    steps:
      - run: echo constant
  release:
    runs-on: ubuntu-latest
    needs: [ constants ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Get version
        id: get-version-raw
        uses: thecodemonkey/action-get-gradle-version@master
        with:
          file: ./api/build.gradle.kts
      - name: Format version string
        id: get-version
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ steps.get-version-raw.outputs.version }}
          find: "'"
          replace: ''
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.value }}-${{ github.run_number }}
          release_name: ${{ steps.get-version.outputs.value }} ${{ github.event.head_commit.message }}
          body: ""
          draft: false
          prerelease: false